name: Review PR Diff

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  reviewmycode:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR code
      - name: Checkout PR Code
        uses: actions/checkout@v2

      # Step 2: Fetch all history for diff
      - name: Fetch All History for Diff
        run: git fetch --all

      # Step 3: Get PR Diff and File Paths with Context
      - name: Get PR Diff with Context
        id: diff
        run: |
          echo "Getting PR diff with 3 lines of context"
          git diff -U3 origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }} > diff.txt

          # Process diff.txt to add line numbers before each added line
          echo "Processing diff to add line numbers..."
          awk '
            /^@@/ {
              split($0, a, " ")
              # Extract the line number where the changes start in the new file
              sub("\\+", "", a[4]) 
              split(a[4], b, ",")
              new_file_line_number = b[1] - 1
              print $0
              next
            }
            /^[+] / {
              new_file_line_number++
              print "+" new_file_line_number ": " substr($0, 2)
              next
            }
            { print $0 }
          ' diff.txt > numbered_diff.txt

      # Step 4: Echo Diff and File Paths
      - name: Echo Diff and File Paths
        run: |
          echo "Numbered Diff content:"
          cat numbered_diff.txt  # Output the processed diff with added line numbers

          echo "File paths:"
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }} > file_paths.txt
          cat file_paths.txt  # Output the content of file_paths.txt

      # Step 5: Send PR Diff and File Paths to Backend for Review
      - name: Send Numbered PR Diff and File Paths to Backend for Review
        run: |
          diff_content=$(cat numbered_diff.txt | jq -Rsa .)
          file_paths=$(cat file_paths.txt | jq -Rsa .)

          echo "Sending Numbered PR Diff for Review"
          curl -X POST "https://app5-latest.onrender.com/openai/api/v2/strategy/4/review-pr-diff" \
          -H "Content-Type: application/json" \
          -d '{
            "diff": '"$diff_content"',
            "owner": "${{ github.repository_owner }}",
            "repo": "${{ github.event.pull_request.head.repo.name }}",
            "prNumber": "${{ github.event.pull_request.number }}",
            "commitId": "${{ github.event.pull_request.head.sha }}",
            "file_paths": '"$file_paths"'
          }'
