name: Comment on PR Diff

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  reviewmycode:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR code
      - name: Checkout PR Code
        uses: actions/checkout@v2

      # Step 2: Fetch all history for diff
      - name: Fetch All History for Diff
        run: git fetch --all

      # Step 3: Get PR Diff from GitHub API and Extract Valid Lines
      - name: Get PR Diff from GitHub API
        id: pr_diff
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.pull_request.head.repo.name }}/pulls/${{ github.event.pull_request.number }}/files" > files.json
          cat files.json

      # Step 4: Parse Diff and Send Comments for Valid Lines
      - name: Send Comments to Valid Lines
        run: |
          # Parse the JSON response to get file paths and valid line numbers
          file_path=$(jq -r '.[0].filename' files.json)
          diff_hunk=$(jq -r '.[0].patch' files.json)

          # Here you need to extract actual lines in the diff where comments will go
          line_number=$(jq -r '.[0].changes' files.json) # Mock line number from the diff

          echo "Sending PR diff comments to backend"
          curl -X POST "https://app5-latest.onrender.com/openai/api/v1/review-pr-diff" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "diff": "$diff_hunk",
            "file_path": "$file_path",
            "line": $line_number,
            "owner": "${{ github.repository_owner }}",
            "repo": "${{ github.event.pull_request.head.repo.name }}",
            "prNumber": "${{ github.event.pull_request.number }}",
            "commitId": "${{ github.event.pull_request.head.sha }}"
          }
          EOF
          echo "Request sent to backend"

      # Step 5: Mock success message
      - name: Print Mock Review Result
        run: echo "Mock review completed. Review comments have been sent."
